-- MySQL Script generated by MySQL Workbench
-- Wed Aug 26 10:59:10 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aeroporto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `aeroporto` ;

-- -----------------------------------------------------
-- Schema aeroporto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aeroporto` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `aeroporto` ;

-- -----------------------------------------------------
-- Table `AERONAVE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AERONAVE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `AERONAVE` (
  `numero_aeronave` INT NOT NULL,
  `fabricante` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`numero_aeronave`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PASSAGEIRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PASSAGEIRO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PASSAGEIRO` (
  `cpf` INT GENERATED ALWAYS AS (),
  `nome_completo` VARCHAR(45) NULL,
  `data_nasc` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PASSAGEIRO_has_VOO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PASSAGEIRO_has_VOO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PASSAGEIRO_has_VOO` (
  `PASSAGEIRO_cpf` INT NOT NULL,
  `VOO_numero_voo` INT NOT NULL,
  PRIMARY KEY (`PASSAGEIRO_cpf`, `VOO_numero_voo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PASSAGEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PASSAGEM` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PASSAGEM` (
  `id_passagem` INT NOT NULL,
  `numero_assento` VARCHAR(45) NULL,
  `classe` VARCHAR(45) NULL,
  `status_checkin` VARCHAR(45) NULL,
  `valor_pago` VARCHAR(45) NULL,
  `data_reserva` VARCHAR(45) NULL,
  `PASSAGEIRO_cpf` INT NOT NULL,
  `VOO_numero_voo` INT NOT NULL,
  `VOO_AERONAVE_numero_aeronave` INT NOT NULL,
  PRIMARY KEY (`id_passagem`, `PASSAGEIRO_cpf`, `VOO_numero_voo`, `VOO_AERONAVE_numero_aeronave`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `VOO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VOO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `VOO` (
  `numero_voo` INT GENERATED ALWAYS AS (),
  `origem` VARCHAR(45) NULL,
  `destino` VARCHAR(45) NULL,
  `horario_partida` VARCHAR(45) NULL,
  `horario_chegada` VARCHAR(45) NULL,
  `AERONAVE_numero_aeronave` INT NOT NULL,
  PRIMARY KEY (`numero_voo`, `AERONAVE_numero_aeronave`))
ENGINE = InnoDB;

SHOW WARNINGS;
USE `aeroporto` ;

-- -----------------------------------------------------
-- View `view1`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `view1` ;
SHOW WARNINGS;
USE `aeroporto`;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
